### ISSUE TITLE
DBSegment not compatible with RTX 3080 GPUs

### ISSUE THREAD

**Issue by jAchtzehn** [luxneuroimage/DBSegment#2]
Hello!

First of all congratulations on this really exciting tool! I was trying to use it with a RTX 3080 NVIDIA GPU but got the following error:

```
Segmenting.
/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/dbssegment/bin/DBSegment", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/DBSegment.py", line 597, in main
    main_infer()
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/DBSegment.py", line 501, in main_infer
    inference(parser)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/DBSegment.py", line 357, in inference
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/inference/predict.py", line 666, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/inference/predict.py", line 218, in predict_cases
    softmax = trainer.predict_preprocessed_data_return_seg_and_softmax(
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/training/network_training/nnUNetTrainerV2.py", line 213, in predict_preprocessed_data_return_seg_and_softmax
    ret = super().predict_preprocessed_data_return_seg_and_softmax(data,
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/training/network_training/nnUNetTrainer.py", line 520, in predict_preprocessed_data_return_seg_and_softmax
    ret = self.network.predict_3D(data, do_mirroring=do_mirroring, mirror_axes=mirror_axes,
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/network_architecture/neural_network.py", line 147, in predict_3D
    res = self._internal_predict_3D_3Dconv_tiled(x, step_size, do_mirroring, mirror_axes, patch_size,
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/network_architecture/neural_network.py", line 386, in _internal_predict_3D_3Dconv_tiled
    predicted_patch = self._internal_maybe_mirror_and_pred_3D(
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/network_architecture/neural_network.py", line 533, in _internal_maybe_mirror_and_pred_3D
    pred = self.inference_apply_nonlin(self(x))
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/DBSegment/nnunet/network_architecture/generic_UNet.py", line 65, in forward
    x = self.conv(x)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 590, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/share/miniconda3/envs/dbssegment/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 585, in _conv_forward
    return F.conv3d(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Is it possible to add compatibility for this GPU as well? 

Thanks!

**Comment by jAchtzehn** [comment]
I was able to fix this myself by installing first the nightly build of pytorch via: 
`pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`

Then, I installed DBSegment as suggested in the readme.
